name: arco_iris
description: A simple printer with style.
version: 0.0.2
repository: https://github.com/Dvergar/arco_iris

environment:
  sdk: ^3.4.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
